### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [zshivers/PlayaNavigator#1]
Hello!

I found this project from https://hackaday.com/2024/02/01/navigate-burning-man-with-ease-with-this-custom-tool/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and PCB hardware files in any purpose?
It would be great to see any popular open source license.

**Comment by zshivers** [comment]
Thanks for the reminder! Added an MIT license.

**Comment by vazhnov** [comment]
MIT license — amazing! Thank you!!!
